### ISSUE TITLE
Payment Acceptance Error Page

### ISSUE THREAD

**Issue by tanoojoy** [Arcadier/Arcadier-support#1]
**Describe the bug**
I have set up Stripe as my payment method on my marketplace. But when one of my merchants tries to link her account to the marketplace she gets an error page

**To Reproduce**
1. Set up Stripe as a payment method, as an Admin
2. Try to onboard as a merchant and link your Stripe Account
3. There is an error page after clicking `Link Account` button

**Expected behavior**
A page where the merchant fills up her details and successfully links her Stripe account to the marketplace

**Screenshots**
![Error Page Stripe](https://user-images.githubusercontent.com/43057493/55399395-9b857b00-557d-11e9-827e-06cb987ec86e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome

**Comment by Arcadier** [comment]
Hi Madison,

Sorry to hear that you are facing difficulties with setting up your payment method. 

We suspect that this issue is caused by the redirect URL being copied over incorrectly.

Could you please check to see that the URL highlighted below has been included onto your Stripe dashboard?
​​ 
<img width="917" alt="Screen Shot 2019-03-27 at 10 12 33 AM" src="https://user-images.githubusercontent.com/6611854/55399631-33836480-557e-11e9-8120-3541fa5db4dd.png">


Do let us know if the problem persists.

Regards,
Chloe from Arcadier

**Comment by tanoojoy** [comment]
Unfortunately the problem you had suspected was the not the issue. I have verified our redirect URL in our admin portal is correct. When our host/seller tries to link Stripe for payments she gets an error page. 

Her paypal is linked and has been verified. Is this causing an issue? In our admin portal we have configured both Stripe and Paypal and both are active but Stripe is chosen as the mandatory payment method.

We are on a tight timeline to ensure that your payment processing system can work so I am hoping you can help me resolve this issue as quickly as possible. 

Please see attachments.

Thank you,
Madison

![Jills Pymt Acc Pg](https://user-images.githubusercontent.com/43057493/55399720-7c3b1d80-557e-11e9-9f5b-6e47b9c143f0.png)
![Error Page Stripe](https://user-images.githubusercontent.com/43057493/55399728-7f360e00-557e-11e9-8689-b801b058768c.png)

**Comment by Arcadier** [comment]
Hey Maddy,


So, as an Admin:

* Login to you marketplace -> Payments and Transactions tab -> Configure Payments -> Click on link account for Stripe
* Click on Login to Stripe. Login to your Administrator's Stripe account.
* On the Stripe Dashboard, on the left panel, just below "Developers", make sure the toggle for "View Test Data" is off/set to the left/grey.
* Go to "Settings" completely at the bottom. In the "Stripe Apps" panel, go to "Connect".
You will then see the "Live Mode Client ID". Copy the ID, it looks something like this: ca_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
* Go to you back to your Admin Dashboard, and paste it in the "Production Client ID" field.
* Still on your admin dashboard, copy your redirect URL.
* Go back to your Stripe Dashboard. Under the Live Client ID, there is the Redirects section. To the right, there is a button called "Add URI". Paste the redirect URL you copied from the Admin Dashboard, and lclick on "Add URI" to save it. It should appear in the list of redirect URIs in the center.
* Next, click on Developers on the left panel; it will drop down. Click on API Keys. You will see a table containing a Publishable Key, and its Token. Copy the token. It starts with a "pk".
* Go back to your Admin Dashboard, scroll up and paste it in the Live Publishable Key field. 
* Go back to your Stripe Dashboard, for the Secret Key click on Reveal live key token. Copy that token. It starts with an "sk". You can now close your stripe dashboard window.
* Go back to your Admin Dashboard and paste that token in the Live Secret Key  field.
* Click on every "Save" button.

That's all that's necessary for the Admin side. Your merchant should be able to link his/her Stripe account when onboarding.
If this does not work, my Skype ID is tanoo.joyekurun. Happy to help you by voice.

Regards,
Tanoo

**Comment by tanoojoy** [comment]
Thank you Tanoo, this seems to have worked. The problem was the URI was missing in the Stripe account. I appreciate the step by step direction as it really helped!

**Comment by Arcadier** [comment]
Hey Maddy,

You're welcome. It was my pleasure to help you and your business.

Sincerely,
Tanoo
